# Generated by Django 5.1.2 on 2024-10-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
